ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using yiran.Models.Entity;

namespace yiran.ViewModels
{
    public class HomeViewModel
    {
        /// <summary>
        /// 网站公共信息
        /// </summary>
        public yr_common common { get; set; }
        /// <summary>
        /// banner
        /// </summary>
        public List<yr_banner> banner { get; set; }
        /// <summary>
        /// 关于我们
        /// </summary>
        public yr_about about { get; set; }
        /// <summary>
        /// 技术支持
        /// </summary>
        public yr_support support { get; set; }
        public List<yr_support_list> support_list { get; set; }
        /// <summary>
        /// 应用领域
        /// </summary>
        public yr_field field { get; set; }
        public List<yr_field_li> field_list { get; set; }
        /// <summary>
        /// 产品
        /// </summary>
        public yr_prouduct product { get; set; }
        public List<yr_prouduct_list> prouduct_list { get; set; }
    }
}

Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using yiran.Areas.Admin.Service;
using yiran.Areas.Admin.Common;
using yiran.Areas.Admin.Models.Entity;
using yiran.Areas.Admin.Models.Request;
using static yiran.Areas.Admin.Common.CommonAttr;

namespace yiran.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly sys_loginService loginService;

        public HomeController(sys_loginService loginService)
        {
            this.loginService = loginService;
        }
        [Sign]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.Get<sys_user>("yr_user") != default)
            {
                var login = new LoginRequest { username = HttpContext.Session.Get<sys_user>("yr_user").username, password = HttpContext.Session.Get<sys_user>("yr_user").password };
                var res = await loginService.Login(login, HttpContext);
                if (res.code == 200)
                {
                    ViewData["name"] = res.data.name;
                    ViewData["menu"] = res.data.sys_menu;
                }
                else
                {
                    HttpContext.Session.Clear();
                    throw new Exception("用户状态有误");
                }
            }
            return View();
        }
        /// <summary>
        /// 修改密码
        /// </summary>
        /// <returns></returns>
        [Sign]
        public IActionResult Repwd() {
            return View();
        }
        [SignApi]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<JsonResult> Repwd(UpdatePwd updatepwd) {
            var res = await loginService.Repwd(updatepwd, HttpContext);
            return Json(res);
        }
    }
}

Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using yiran.Areas.Admin.Common;
using yiran.Areas.Admin.Models.Request;
using yiran.Areas.Admin.Models.Response;
using yiran.Areas.Admin.Service;
using yiran.Tools;
using static yiran.Areas.Admin.Common.CommonAttr;

namespace yiran.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LoginController : Controller
    {
        private readonly sys_loginService loginService;

        public LoginController(sys_loginService loginService)
        {
            this.loginService = loginService;
        }
        public IActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 登录
        /// </summary>
        /// <param name="login"></param>
        /// <returns></returns>
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [IsModel]
        public async Task<JsonResult> Index(LoginRequest login)
        {
            //登录接口限制
            if (!string.IsNullOrEmpty(HttpContext.Session.Get<string>("old_time")))
            {
                DateTime old_time = Convert.ToDateTime(HttpContext.Session.Get<string>("old_time"));
                DateTime new_time = DateTime.Now;
                TimeSpan ts = new_time - old_time;
                double time = ts.TotalMilliseconds;
                if (time <= 1000)
                {
                    return Json(new ResponseModel { code = 0, result = "稍后再试" }); ;
                }
            }
            HttpContext.Session.Set<string>("old_time", DateTime.Now.ToString());
            login.password = ToolBase.EncryptByMd5(login.password);
            var res = await loginService.Login(login, HttpContext);
            res.data = "";
            return Json(res);
        }
        public JsonResult Logout()
        {
            HttpContext.Session.Clear();
            return Json(new ResponseModel { code = 200, result = "退出登录~" });
        }
    }
}

Areas/Admin/Controllers/WelcomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using yiran.Areas.Admin.Common;
using yiran.Areas.Admin.Models.Entity;
using yiran.Tools;
using static yiran.Areas.Admin.Common.CommonAttr;

namespace yiran.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Sign]
    public class WelcomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["service"] = RuntimeInformation.OSDescription; //获取服务器信息
            ViewData["sdk"] = RuntimeInformation.FrameworkDescription; //获取sdk版本
            ViewData["UploadMax"] = (int.Parse(ToolBase.GetSectionValue("UploadMax")) / 1024).ToString();

            if (HttpContext.Session.Get<sys_user>("yr_user") != default)
            {
                ViewBag.UserName = HttpContext.Session.Get<sys_user>("yr_user").name;
            }

            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using yiran.Models.Entity;
using yiran.Models.Request;
using yiran.Services;
using yiran.ViewModels;
using static yiran.Areas.Admin.Common.CommonAttr;

namespace yiran.Controllers
{
    public class HomeController : Controller
    {
        private readonly HomeService _homeService;

        public HomeController(HomeService homeService)
        {
            this._homeService = homeService;
        }
        public async Task<IActionResult> Index()
        {
            Task<yr_common> common = _homeService.GetCommon();
            Task<List<yr_banner>> banner = _homeService.GetAllBanner();
            Task<yr_about> about = _homeService.GetAbout();
            Task<yr_support> support = _homeService.GetSupport();
            Task<List<yr_support_list>> support_list = _homeService.GetSupportList();
            Task<yr_field> field = _homeService.GetField();
            Task<List<yr_field_li>> field_list = _homeService.GetFieldList();
            Task<yr_prouduct> product = _homeService.GetProduct();
            Task<List<yr_prouduct_list>> prouduct_list = _homeService.GetProductList();
            var ViewModel = new HomeViewModel {
                common = await common,
                banner = await banner,
                about = await about,
                support = await support,
                support_list = await support_list,
                field = await field,
                field_list = await field_list,
                product = await product,
                prouduct_list = await prouduct_list
            };
            ViewData["description"] = RemoveHTML(ViewModel.common.description);
            ViewData["keywords"] = RemoveHTML(ViewModel.common.keywords);
            ViewData["title"] = RemoveHTML(ViewModel.common.title);
            return View(ViewModel);
        }
        /// <summary>
        /// 产品详情页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id) {
            if (id == 0)
            {
                return View("Error");
            }
            else {
                
                if (string.IsNullOrEmpty(GetCookies("number")))
                {
                    SetCookies("number", id.ToString());
                    var numberadd = _homeService.AddNumber(id);
                }
                else {
                    var ids = GetCookies("number").Split(",");
                    if (Array.IndexOf(ids, id.ToString()) == -1)
                    {
                        SetCookies("number", GetCookies("number") + "," + id.ToString());
                        var numberadd = _homeService.AddNumber(id);
                    }
                }
                var product = await _homeService.GetOneProduct(id);
                var ViewModel = new DetailsViewModel
                {
                    common = await _homeService.GetCommon(),
                    product = product,
                    prevproduct = await _homeService.GetPrevProduct(id),
                    nextproduct = await _homeService.GetNextProduct(id)
                };
                ViewData["description"] = RemoveHTML(product.content);
                ViewData["keywords"] = RemoveHTML(product.content);
                return View(ViewModel);
            }
        }
        /// <summary>
        /// 留言
        /// </summary>
        /// <param name="addform"></param>
        /// <returns></returns>
        [HttpPost]
        [IsModel]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AddJoin(addform addform) {
            var res = await _homeService.AddJoin(addform);
            return Json(res);
        }

        /// <summary>
        /// 错误页
        /// </summary>
        /// <returns></returns>
        public IActionResult Error()
        {
            return View();
        }
        /// <summary>
        /// 设置本地cookie
        /// </summary>
        /// <param name="key">键</param>
        /// <param name="value">值</param>  
        /// <param name="minutes">过期时长，单位：分钟</param>      
        protected void SetCookies(string key, string value, int minutes = 30)
        {
            HttpContext.Response.Cookies.Append(key, value, new CookieOptions
            {
                Expires = DateTime.Now.AddMinutes(minutes)
            });
        }
        /// <summary>
        /// 删除指定的cookie
        /// </summary>
        /// <param name="key">键</param>
        protected void DeleteCookies(string key)
        {
            HttpContext.Response.Cookies.Delete(key);
        }

        /// <summary>
        /// 获取cookies
        /// </summary>
        /// <param name="key">键</param>
        /// <returns>返回对应的值</returns>
        protected string GetCookies(string key)
        {
            HttpContext.Request.Cookies.TryGetValue(key, out string value);
            if (string.IsNullOrEmpty(value))
                value = string.Empty;
            return value;
        }
        protected string RemoveHTML(string Htmlstring)
        {
            if (string.IsNullOrEmpty(Htmlstring)) { return ""; }
            //删除脚本
            Htmlstring = Regex.Replace(Htmlstring, @"<script[^>]*?>.*?</script>", "", RegexOptions.IgnoreCase);
            //删除HTML
            Htmlstring = Regex.Replace(Htmlstring, @"<(.[^>]*)>", "", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"([\r\n])[\s]+", "", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"-->", "", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"<!--.*", "", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(quot|#34);", "\"", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(amp|#38);", "&", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(lt|#60);", "<", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(gt|#62);", ">", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(nbsp|#160);", " ", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(iexcl|#161);", "\xa1", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(cent|#162);", "\xa2", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(pound|#163);", "\xa3", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&(copy|#169);", "\xa9", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"&#(\d+);", "", RegexOptions.IgnoreCase);
            Htmlstring = Regex.Replace(Htmlstring, @"<img[^>]*>;", "", RegexOptions.IgnoreCase);
            Htmlstring.Replace("<", "");
            Htmlstring.Replace(">", "");
            Htmlstring.Replace("\r\n", "");
            return Htmlstring;
        }
    }
}

Areas/Admin/Views/Home/Index.cshtml

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<body class="index">
    <!-- 顶部开始 -->
    <div class="container">
        <div class="logo">
            <a href="@Url.Action("Index","Home",new { area="Admin"})">后台管理</a>
        </div>
        <div class="left_open">
            <a><i title="展开左侧栏" class="iconfont">&#xe699;</i></a>
        </div>

        <ul class="layui-nav right" lay-filter="">
            <li class="layui-nav-item">
                <a href="javascript:;">@ViewData["name"]</a>
                <dl class="layui-nav-child">
                    <!-- 二级菜单 -->
                    <dd>
                        <a onclick="xadmin.open('修改密码','@Url.Action("Repwd","Home",new { area = "admin"})',700,600)">修改密码</a>
                    </dd>
                    <dd>
                        <a href="javascript:;" onclick="Logout()">退出</a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item to-index">
                <a href="/">前台首页</a>
            </li>
        </ul>
    </div>
    <!-- 顶部结束 -->
    <!-- 中部开始 -->
    <!-- 左侧菜单开始 -->
    <div class="left-nav">
        <div id="side-nav">
            <ul id="nav">
                @using yiran.Areas.Admin.Models.Entity
                @foreach (var menu in ViewData["menu"] as List<sys_menu>)
                {
                    @if (menu.parent_id == 0)
                    {
                        <li>
                            <a href="javascript:;">
                                <i class="iconfont left-nav-li" lay-tips="@menu.name">@Html.Raw(@menu.icon)</i>
                                <cite>@menu.name</cite>
                                <i class="iconfont nav_right">&#xe6a6;</i>
                            </a>
                            <ul class="sub-menu">
                                @foreach (var submenu in (ViewData["menu"] as List<sys_menu>).Where(c => c.parent_id == menu.id))
                                {
                                    @if (string.IsNullOrEmpty(submenu.action))
                                    {
                                        <li>
                                            <a onclick="xadmin.add_tab('@submenu.name','@submenu.path','@menu.name')">
                                                <i class="iconfont">&#xe6a7;</i>
                                                <cite>@submenu.name</cite>
                                            </a>
                                        </li>
                                    }
                                }
                            </ul>
                        </li>
                    }
                }


            </ul>
        </div>
    </div>
    <!-- <div class="x-slide_left"></div> -->
    <!-- 左侧菜单结束 -->
    <!-- 右侧主体开始 -->
    <div class="page-content">
        <div class="layui-tab tab" lay-filter="xbs_tab" lay-allowclose="false">
            <ul class="layui-tab-title">
                <li class="home">
                    <i class="layui-icon">&#xe68e;</i>我的桌面
                </li>
            </ul>
            <div class="layui-unselect layui-form-select layui-form-selected" id="tab_right">
                <dl>
                    <dd data-type="this">关闭当前</dd>
                    <dd data-type="other">关闭其它</dd>
                    <dd data-type="all">关闭全部</dd>
                </dl>
            </div>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show">
                    <iframe src='@Url.Action("Index","Welcome",new { area="Admin"})' frameborder="0" scrolling="yes" class="x-iframe"></iframe>
                </div>
            </div>
            <div id="tab_show"></div>
        </div>
    </div>
    <div class="page-content-bg"></div>
    <style id="theme_style"></style>
    <!-- 右侧主体结束 -->
    <!-- 中部结束 -->
    <script>
        function Logout() {
            layer.confirm('确定要离开嘛？', function (index) {
                $.get("@Url.Action("Logout","Login",new { area="Admin"})", function (data) {
                    layer.msg(data.result, {
                        icon: 1,
                        time: 2000
                    }, function () {
                        location.reload();
                    });
                })
            });
        }
    </script>
</body>

Areas/Admin/Views/Home/Repwd.cshtml

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<body>
    <div class="layui-fluid">
        <div class="layui-row">
            <form class="layui-form" lay-filter="example">
                <div class="layui-form-item">
                    <label for="username" class="layui-form-label">
                        <span class="x-red">*</span>
                        旧密码
                    </label>
                    <div class="layui-input-inline">
                        <input style="height:38px;" required lay-verify="required" value="" type="password" name="oldpwd" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="username" class="layui-form-label">
                        <span class="x-red">*</span>
                        新密码
                    </label>
                    <div class="layui-input-inline">
                        <input style="height:38px;" required lay-verify="required" id="L_pass" value="" type="password" name="newpwd" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="username" class="layui-form-label">
                        <span class="x-red">*</span>
                        确认密码
                    </label>
                    <div class="layui-input-inline">
                        <input style="height:38px;" required lay-verify="repass" id="L_repass" value="" type="password" name="repwd" autocomplete="off" class="layui-input">
                    </div>
                </div>
                @Html.AntiForgeryToken()
                <div class="layui-form-item" style="margin-top:20px">
                    <button class="layui-btn layui-btn-lg" lay-filter="add" style="display:block;margin:auto" lay-submit="">
                        修改
                    </button>
                </div>
            </form>
        </div>
    </div>
    <script>
        layui.use(['form', 'layer','element','upload'],

            function() {
                $ = layui.jquery;
                var form = layui.form,
                    layer = layui.layer,
                    upload = layui.upload;
                //自定义验证规则
                form.verify({
                    repass: function(value) {
                        if ($('#L_pass').val() != $('#L_repass').val()) {
                            return '两次密码不一致';
                        }
                    }
                });
                //监听提交
                form.on('submit(add)',
                    function (data) {
                        var index = layer.load(1);
                        var dataf = data.field;
                    $.ajax({
                        url: '@Url.Action("Repwd","Home",new { area="Admin"})',
                        data: dataf,
			            type: "post",
			            async:true,
			            dataType: 'json',
                        success: function (data) {
                            if (data.code == 200) {
                                //发异步，把数据提交给php
                                layer.msg(data.result, function () {
                                    //关闭当前frame
                                    xadmin.close();
                                    // 可以对父窗口进行刷新
                                    parent.location.replace("/admin/login")
                                });
                            } else {
                                 layer.msg(data.result, { icon: 0, time: 2000 });
                            }
                        },
			            error:function(xhr,errorText,errorType){
                             alert("error");
                        },
			            complete : function(XMLHttpRequest,status){ //请求完成后最终执行参数
				            if(status=='timeout'){
					            ajax.abort();
					            alert("请求超时");
                            }
                            layer.close(index);
			            }
		            })

                    return false;
                });

            });
    </script>
</body>